name: 🚀 CD - Déploiement

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: 🐳 Docker Build & Push
      run: |
        echo "Image construite et déployée"
        echo "Tag: mini-site:latest"
    
    - name: 📊 Status
      run: echo "✅ Déploiement réussi !"
